version: '3.9'

services:
  frontend:
    build:
      context: ./todo-list-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build:
      context: ./todo-list-backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ToDoList
    volumes:
      - ./postgres-data:/var/lib/postgresql/data